USE [USER_DATABASE]
GO

ALTER FUNCTION [dbo].[fnUtcToLocalDate] (@DateUTC DATETIME)
RETURNS DATETIME
AS
BEGIN

	RETURN CONVERT( datetime, SWITCHOFFSET( CONVERT( datetimeoffset, @DateUTC ), DATENAME(TzOffset, SYSDATETIMEOFFSET() ) ) ) 

END
