USE [USER_DATABASE]
GO

ALTER PROCEDURE [dbo].[PR_REPORT_ACESSOS_POR_DATAHORA] 
(
		@DT_INICIAL		AS DATE
	,	@DT_FINAL		AS DATE
)
AS
	SELECT		    R.DATA
	,				R.HORA	
	,				R.DT_INICIO		AS	DATA_HORA
	,				R.ENDERECO_IP
	,				R.SESSAO
	,				R.USUARIO			AS	LOGIN
	,				R.DURACAO
	,				R.ENTRADA			AS UPLOAD
	,				R.SAIDA				AS	DOWNLOAD
	,				R.NOME_CLIENTE
	,				R.LABEL_CPF_CNPJ
	,				R.CPF_CNPJ
	FROM			dbo.FnListaAcessoCliente( @DT_INICIAL, @DT_FINAL, NULL ) R
	ORDER BY 	R.DT_INICIO